### ISSUE TITLE
How to get ".xml" file

### ISSUE THREAD

**Issue by yanzheng9527** [rggasoto/DriveGG#1]
Hello,
 In "createcsv.py", we need ".xml" file, how to create it?
With Regards,
Yan

**Comment by rggasoto** [comment]
In the case of GTA V, I generated the XML using class serialization on the features I wanted to extract. The createcsv.py script is modeled after that structure and needs to be in the folder where the dataset is recorded. 

Check [this section of the repo](https://github.com/rggasoto/DriveGG/tree/master/GTA%20V/GetWorldInfoRecord) to see how the game script structures the data and records the dataset.
