### ISSUE TITLE
multiple cameras

### ISSUE THREAD

**Issue by piliwilliam0306** [rggasoto/DriveGG#2]
Hi @rggasoto ,

Great work! Is it possible to add multiple cameras so we can get more augmented data?

Thanks!

**Comment by rggasoto** [comment]
I'd love to have that functionality too! I believe it might be possible but need to work on the GPU pipeline for that. So far attempts to have multiple viewports such as in 'split-screen' modes using only the available functions provided by scripthook were unsuccessful.
