### ISSUE TITLE
Workflow for testing

### ISSUE THREAD

**Issue by Duskfall** [rggasoto/DriveGG#3]
First of all I want to say great work! I use your example to learn the simulation and want to also add the computer vision logic for traffic lights and stop signs. I want to make a simulation like yours for my thesis.
If you have the time please clarify some aspects that are troubling me. I have successfully added the mods/dlls in GTA, compiled and added the C# projects and joystick, and recorded new images and xml files in game. I have trained the model with much smaller dataset though just to play around and now I want to run it.
Two problems I have found.
First of all in jupiter, `histogram_gta_data.index` is an IntervalIndex which cannot be plotted. This is true in new versions of pandas. [See here](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.IntervalIndex.html)
Second of all, I try to load my generated model to drive.py but do I need to use [DeepGTAV](https://github.com/ai-tor/DeepGTAV) for that too? I see that you use a flask application and an eventlet server. Can you add a little documentation of what is needed for these to work?
Thanks in advance!

**Comment by rggasoto** [comment]
Hello! Thank you for your compliments!
I'm not using jupiter notebooks, so I don't follow what is the issue with the histogram_gta_data.index, could you elaborate on what you are trying to do?

for the second question, The drive.py uses a socket for communication with the controller emulator, on a very simple interface, all you should have is the socket package on your python installation and you should be good to go.
This project is completely unrelated to DeepGTAV, so you wouldn't need it.
to run drive.py, you just have to pass on the name of your json dataset, e.g:

`python drive.py nvidia_4.json` will load the nvidia_4 model and weights
